### PR TITLE
Hi, I've fixed some issues I had specially with encoding. Plus I added a simple feature.

### PR DESCRIPTION
**Pull request by Termit1975**
First bug: When creating Attachments from Mime, date properties stored in the Mime entity, when were transferred over the Attachment, I had parsing exception because the date string was not in the correct format. Since after copying the key one by one, the existing code was setting those dates, I decided to skip them and rely on the fact that those properties were set after the loop.

Second bug: When going through QuotedPrintableEncoding, I end up with extra '=' characters, the algorithm should not append the '=' character since it is only an indication that the line was breaked and continues. 

Third bug: When decoding a small line with QuotedPrintableEncoding. Example: Fr=E9d=E9ric, I was getting a decoded string equal to "Frédéric\r\n", the algorithm should not add an extra line break if the line does not end with an equal and is the last line of the stream...

Fourth bug: When receiving e-mail containing special characters such as ç that not b or q encoded ie: Content-Transfer-Encoding: 8bit, StreamReader was not able to process the characters correctly.

Feature: I added the possibility to get the initial content of the message as part of the MimeEntity. This is specially useful for us because we would like to attach in our system the original message. Saving the "RawMessage" as Something.eml file would display perfectly fine in Outlook, Lotus, Windows Live mail when opening the file in windows explorer. It is also very useful if any parsing error occurs, this would allow reprocessing the original e-mail and figure where is the parsing error.

Thanks for considering my contributions.

### CODE REVIEW

**Comment by ferventcoder** [comment]
Whoa, here's what happens when you don't have notifications turned on. :(

Why How much of this do you think is still relevant?

**Comment by ferventcoder** [comment]
@Termit1975 sorry about not seeing this. I've updated myself to watch this repo now.

**Comment by Termit1975** [comment]
Well lot of stuff has been going on on our side. We build an application which interacts with almost every external email systems (from notes, exchange, novel, and all the crappy email APIs out there). We are mainly doing this in french which has accents characters everywhere. We treat like 10 thousands emails a day among our 400 clients. Now the code is pretty much stabilized and support any encoding. We also have a bunch of test (raw email from our clients that were not parsed correctly and used these test cases to fix some issues). They are not included in the repo for confidentiality issues.

**Comment by ferventcoder** [comment]
That's fine. I don't have a problem pulling this in.

**Comment by ferventcoder** [comment]
From now on though, all PRs should be submitted from branches other than master. :)

**Pull request merged**
